export const types = {
  login: '[auth] login',
  logout: '[auth] logout',
  uiSetError: '[ui] Set Error',
  uiRemoveError: '[ui] Remove Error',
  uiStartLoading: '[ui] Start loading',
  uiFinishLoading: '[ui] Finish loading',
  heroesAddNew: '[heroes] Add new',
  heroesActive: '[heroes] Set active',
  heroesLoad: '[heroes] Load',
  heroesUpdated: '[heroes] Updated',
  heroesFileUrl: '[heroes] Updated image url',
  heroesDelete: '[heroes] Delete',
  heroesLogoutCleaning: '[heroes] Logout Cleaning',
};
